name: Deploy

on: [ push ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: RUN DEPLOY
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ vars.HOST }}
          username: ${{ vars.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ vars.PORT }}
          script: |
            cd /home/hsuan/web-ionc
            bash ./update.sh